In [1]:
import pandas as pd
data = ({
    "Age": [25, 30, 35, 40, 45],
    "Income": [30000, 45000, 60000, 70000, 90000],
    "Spending": [500, 800, 1200, 1600, 2200]
})

data = pd.DataFrame(data)
print(data)

   Age  Income  Spending
0   25   30000       500
1   30   45000       800
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [2]:
data.head(3)

   Age  Income  Spending
0   25   30000       500
1   30   45000       800
2   35   60000      1200

In [3]:
data.tail(3)

   Age  Income  Spending
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [4]:
data.shape

(5, 3)

In [5]:
data.columns

Index(['Age', 'Income', 'Spending'], dtype='object')

In [6]:
data.columns.tolist()

['Age', 'Income', 'Spending']

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       5 non-null      int64
 1   Income    5 non-null      int64
 2   Spending  5 non-null      int64
dtypes: int64(3)
memory usage: 248.0 bytes

In [8]:
data.dtypes

Age         int64
Income      int64
Spending    int64
dtype: object

In [9]:
data.describe()

             Age        Income     Spending
count   5.000000      5.000000     5.000000
mean   35.000000  59000.000000  1260.000000
std     7.905694  23021.728866   669.328021
min    25.000000  30000.000000   500.000000
25%    30.000000  45000.000000   800.000000
50%    35.000000  60000.000000  1200.000000
75%    40.000000  70000.000000  1600.000000
max    45.000000  90000.000000  2200.000000

In [10]:
data["Age"]

0    25
1    30
2    35
3    40
4    45
Name: Age, dtype: int64

In [11]:
data[["Age", "Spending"]]

   Age  Spending
0   25       500
1   30       800
2   35      1200
3   40      1600
4   45      2200

In [12]:
data[data["Income"] > 50000]

   Age  Income  Spending
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [13]:
data[data["Age"] > 25]

   Age  Income  Spending
1   30   45000       800
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [14]:
data[(data["Income"] > 50000) & (data["Age"] > 30)]

   Age  Income  Spending
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [15]:
data[(data["Income"] > 50000) | (data["Age"] > 40)]

   Age  Income  Spending
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [16]:
data[data["Age"] == 40]

   Age  Income  Spending
3   40   70000      1600

In [17]:
import pandas as pd
data2 = ({
    "Age": [25, "", 35, 40, 45],
    "Income": [30000, "", 60000, 70000, 90000],
    "Spending": [500, "", 1200, 1600, 2200]
})

data2 = pd.DataFrame(data2)
print(data2)

  Age Income Spending
0  25  30000      500
1
2  35  60000     1200
3  40  70000     1600
4  45  90000     2200

In [18]:
data2.isnull().sum()

Age         0
Income      0
Spending    0
dtype: int64

In [19]:
data2.dropna()

  Age Income Spending
0  25  30000      500
1
2  35  60000     1200
3  40  70000     1600
4  45  90000     2200

In [20]:
data.dropna()

   Age  Income  Spending
0   25   30000       500
1   30   45000       800
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [21]:
data2["Age"] = data2["Age"].fillna(data2["Age"].mode())
data2["Age"]

0    25
1
2    35
3    40
4    45
Name: Age, dtype: object

In [22]:
data2.dropna()

  Age Income Spending
0  25  30000      500
1
2  35  60000     1200
3  40  70000     1600
4  45  90000     2200

In [23]:
data["Income"] = data["Income"].fillna(data["Income"].mean())
data["Income"]

0    30000
1    45000
2    60000
3    70000
4    90000
Name: Income, dtype: int64

In [24]:
data1 = ({
    "Age": [25, 30, 35],
    "Income": [30000, 45000, 60000],
    "City": ["Kigali", "Huye", "Kigali"]
})

data1 = pd.DataFrame(data1)
print(data1)

   Age  Income    City
0   25   30000  Kigali
1   30   45000    Huye
2   35   60000  Kigali

In [25]:
pd.get_dummies(data1, columns=["City"])

   Age  Income  City_Huye  City_Kigali
0   25   30000      False         True
1   30   45000       True        False
2   35   60000      False         True

In [26]:
pd.get_dummies(data1, columns=["City"])

   Age  Income  City_Huye  City_Kigali
0   25   30000      False         True
1   30   45000       True        False
2   35   60000      False         True

In [27]:
data1

   Age  Income    City
0   25   30000  Kigali
1   30   45000    Huye
2   35   60000  Kigali

In [28]:
data1 = data1.drop("City", axis = 1)
data1

   Age  Income
0   25   30000
1   30   45000
2   35   60000

In [29]:
data1 = data1.rename(columns={"Income": "Monthly Income"})
data1

   Age  Monthly Income
0   25           30000
1   30           45000
2   35           60000

In [30]:
data1 = data1.rename(columns={"Age": "Age of Customers"})
data1

   Age of Customers  Monthly Income
0                25           30000
1                30           45000
2                35           60000

In [31]:
data1

   Age of Customers  Monthly Income
0                25           30000
1                30           45000
2                35           60000

In [33]:
data1["Annual_Income"] = data1["Monthly Income"] * 12

In [34]:
data1

   Age of Customers  Monthly Income  Annual_Income
0                25           30000         360000
1                30           45000         540000
2                35           60000         720000

In [35]:
data1.sort_values("Monthly Income")

   Age of Customers  Monthly Income  Annual_Income
0                25           30000         360000
1                30           45000         540000
2                35           60000         720000

In [36]:
data1.sort_values("Monthly Income", ascending=False)

   Age of Customers  Monthly Income  Annual_Income
2                35           60000         720000
1                30           45000         540000
0                25           30000         360000

In [37]:
data1.sort_values("Monthly Income", ascending=True)

   Age of Customers  Monthly Income  Annual_Income
0                25           30000         360000
1                30           45000         540000
2                35           60000         720000

In [38]:
data1[data1["Monthly Income"] >50000]

   Age of Customers  Monthly Income  Annual_Income
2                35           60000         720000

In [44]:
data1[(data1["Age of Customers"] == 30) & (data1["Annual_Income"] == 540000)]

   Age of Customers  Monthly Income  Annual_Income
1                30           45000         540000

In [46]:
data1.loc[data1["Monthly Income"] > 50000]

   Age of Customers  Monthly Income  Annual_Income
2                35           60000         720000

In [50]:
data1.loc[data1["Monthly Income"] > 50000, ["Age of Customers", "Monthly Income"]]

   Age of Customers  Monthly Income
2                35           60000

In [53]:
data1.iloc[0]

Age of Customers        25
Monthly Income       30000
Annual_Income       360000
Name: 0, dtype: int64

In [54]:
data1.iloc[0:3]

   Age of Customers  Monthly Income  Annual_Income
0                25           30000         360000
1                30           45000         540000
2                35           60000         720000

In [55]:
data1.iloc[:, 0:2]

   Age of Customers  Monthly Income
0                25           30000
1                30           45000
2                35           60000

In [56]:
data.duplicated().sum()

np.int64(0)

In [57]:
data1.duplicated().sum()

np.int64(0)

In [58]:
data1.duplicated().sum()

np.int64(0)

In [59]:
data1.duplicated().sum()

np.int64(0)

In [60]:
data1.drop_duplicates()

   Age of Customers  Monthly Income  Annual_Income
0                25           30000         360000
1                30           45000         540000
2                35           60000         720000

In [61]:
data.drop_duplicates()

   Age  Income  Spending
0   25   30000       500
1   30   45000       800
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [62]:
data.duplicated().sum()

np.int64(0)

In [63]:
data.head()

   Age  Income  Spending
0   25   30000       500
1   30   45000       800
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [64]:
data.tail()

   Age  Income  Spending
0   25   30000       500
1   30   45000       800
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [65]:
data.shape

(5, 3)

In [66]:
data.columns

Index(['Age', 'Income', 'Spending'], dtype='object')

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       5 non-null      int64
 1   Income    5 non-null      int64
 2   Spending  5 non-null      int64
dtypes: int64(3)
memory usage: 248.0 bytes

In [68]:
data.describe()

             Age        Income     Spending
count   5.000000      5.000000     5.000000
mean   35.000000  59000.000000  1260.000000
std     7.905694  23021.728866   669.328021
min    25.000000  30000.000000   500.000000
25%    30.000000  45000.000000   800.000000
50%    35.000000  60000.000000  1200.000000
75%    40.000000  70000.000000  1600.000000
max    45.000000  90000.000000  2200.000000

In [69]:
data.isnull().sum()

Age         0
Income      0
Spending    0
dtype: int64

In [70]:
data.duplicated().sum()

np.int64(0)

In [71]:
data.drop_duplicates()

   Age  Income  Spending
0   25   30000       500
1   30   45000       800
2   35   60000      1200
3   40   70000      1600
4   45   90000      2200

In [72]:
data["Income"] = data["Income"].fillna(data["Income"].mode())
data["Income"]

0    30000
1    45000
2    60000
3    70000
4    90000
Name: Income, dtype: int64

In [73]:
data1

   Age of Customers  Monthly Income  Annual_Income
0                25           30000         360000
1                30           45000         540000
2                35           60000         720000

In [75]:
data2

  Age Income Spending
0  25  30000      500
1
2  35  60000     1200
3  40  70000     1600
4  45  90000     2200

In [83]:
import pandas as pd

dat1 = pd.DataFrame({
    "Gender": ["Male", "Female", "Female", "Male", "Male"]
})

print(dat1)

   Gender
0    Male
1  Female
2  Female
3    Male
4    Male

In [84]:
dat1["Gender"] = dat1["Gender"].map({
    "Male": 1,
    "Female": 0
})

In [85]:
dat1

   Gender
0       1
1       0
2       0
3       1
4       1